redis:
  port: 6379
  host: 127.0.0.1
  auth: false

cookie:
  secret: w@tever
  key: jsessionid

session:
  secret: w@tever-s3ss!@n

mongo: mongodb://plume_dev:Welcome2010!@ds048877-a0.mongolab.com:48877,ds048877-a1.mongolab.com:48876/plume_dev

apn:
  production: false
  key: './config/key.pem'
  cert: './config/cert.pem'
  passphrase: Welcome2010!

redis_data:
  port: 6379
  host: plumechatload.redis.cache.windows.net
  auht: xByyLOwqvzSr968LifvC6KJo0NSGfLVy+4qRoagPTbk=