redis:
  port: 6379
  host: 127.0.0.1
  auth: false

cookie:
  secret: w@tever
  key: jsessionid

session:
  secret: w@tever-s3ss!@n

mongo: mongodb://plumedev:Welcome2010!@ds050077.mongolab.com:50077/plumedev

apn:
  production: false
  key: './config/key.pem'
  cert: './config/cert.pem'
  passphrase: Welcome2010!